### ISSUE TITLE
Are You Back Viki?

### ISSUE THREAD

**Issue by thedhruvkumar** [vikixx13/vikibot-public#3]
- Any Plan to Continue Discord bot development? 
- Are You coming back ?
- @vikixx13

**Comment by vikixx13** [comment]
- not now my mid sems going on ,but yes whenever I have free time i'll continue learning and implementing bot dev 

- Thanks for all the contris till now i'll definitely require your help if I have any doubts moving forward

- @thedhruvkumar

**Comment by thedhruvkumar** [comment]
- Thanks for your positive feedback 
- Also Best of luck for your mid sems
- see you soon @vikixx13
